package thames.sterling.loans.model.applicant.service.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 24 05:26:41 BST 2017
// ---------------------------------------------------------------------
public interface ApplicantService extends ApplicationModule {
    Map initializeObjects(Map in);
}

