package thames.sterling.loans.model.admin.setup.service;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 22 00:38:37 BST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminSetupServiceImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AdminSetupServiceImpl() {
    }

    /**
     * Container's getter for LoanTypes.
     * @return LoanTypes
     */
    public ViewObjectImpl getLoanTypes() {
        return (ViewObjectImpl) findViewObject("LoanTypes");
    }
}

