package thames.sterling.loans.model.loanengine.service;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 22 00:35:33 BST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoanEngineServiceImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LoanEngineServiceImpl() {
    }

    /**
     * Container's getter for LoanAgreements.
     * @return LoanAgreements
     */
    public ViewObjectImpl getLoanAgreements() {
        return (ViewObjectImpl) findViewObject("LoanAgreements");
    }

    /**
     * Container's getter for StaffJobRoles.
     * @return StaffJobRoles
     */
    public ViewObjectImpl getStaffJobRoles() {
        return (ViewObjectImpl) findViewObject("StaffJobRoles");
    }

    /**
     * Container's getter for Staff.
     * @return Staff
     */
    public ViewObjectImpl getStaff() {
        return (ViewObjectImpl) findViewObject("Staff");
    }
}

