--------------------------------------------------------
--  File created - Wednesday-May-24-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TSL_APLCNT_ADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_APLCNT_ADDRESS" 
   (	"APLCNT_ADDRESS_ID" NUMBER(18,0), 
	"APPLICANT_ID" NUMBER(18,0), 
	"ADDRESS_LINE_1" VARCHAR2(240 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(240 BYTE), 
	"ADDRESS_LINE_3" VARCHAR2(240 BYTE), 
	"POST_CODE" VARCHAR2(20 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."APLCNT_ADDRESS_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."APPLICANT_ID" IS 'Reference to APPLICANT_ID in TSL_APLCNT_PER_DETAILS table.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."ADDRESS_LINE_1" IS 'Line 1 in the address details of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."ADDRESS_LINE_2" IS 'Line 2 in the address details of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."ADDRESS_LINE_3" IS 'Line 3 in the address details of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."POST_CODE" IS 'Postal code of the applicant address.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."START_DATE" IS 'The date applicant started living in this address.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."END_DATE" IS 'The date applicant moved out from the address.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_ADDRESS"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Table TSL_APLCNT_FIN_DTLS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_APLCNT_FIN_DTLS" 
   (	"FIN_DETAILS_ID" NUMBER(18,0), 
	"APPLICANT_ID" NUMBER(18,0), 
	"LOAN_AMOUNT" NUMBER, 
	"LOAN_TERM_MONTHS" NUMBER(5,0), 
	"LOAN_TERM_YEARS" NUMBER(5,0), 
	"LOAN_PURPOSE" NUMBER(18,0), 
	"MONTHLY_NET_INCOME" NUMBER(19,4), 
	"EMPLOYMENT_TYPE" NUMBER(18,0), 
	"NO_OF_DEPENDENTS" NUMBER(2,0), 
	"NO_OF_HOUSE_HOLDS_EARNING" NUMBER(2,0), 
	"EXISTED_DEBT_AMOUNT" NUMBER(19,4), 
	"ANY_BANKRUPTCIES_FLAG" VARCHAR2(1 BYTE), 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."FIN_DETAILS_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."APPLICANT_ID" IS 'Reference to APPLICANT_ID in TSL_APLCNT_PER_DETAILS table.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."LOAN_AMOUNT" IS 'Loan amount requested by the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."LOAN_TERM_MONTHS" IS 'Loan repayment period in months requested by the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."LOAN_TERM_YEARS" IS 'Loan repayment period in years requested by the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."LOAN_PURPOSE" IS 'What purpose the applicant will use the loan amount.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."MONTHLY_NET_INCOME" IS 'What is the monthly net income. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."EMPLOYMENT_TYPE" IS 'What is the employment type. Example: Employed, Contract, Self Emloyed.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."NO_OF_DEPENDENTS" IS 'Number of depenedents of the application.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."NO_OF_HOUSE_HOLDS_EARNING" IS 'Number of house holds earning in the house.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."EXISTED_DEBT_AMOUNT" IS 'Existed debt amount for the applicant. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."ANY_BANKRUPTCIES_FLAG" IS 'Were there any bankruptcises to the applicant. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_FIN_DTLS"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Table TSL_APLCNT_PER_DETAILS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" 
   (	"APPLICANT_ID" NUMBER(18,0), 
	"TITLE" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"MIDDLE_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"MOBILE_NUMBER" VARCHAR2(60 BYTE), 
	"HOME_PHONE_NUMBER" VARCHAR2(60 BYTE), 
	"E_MAIL_ID" VARCHAR2(254 BYTE), 
	"LOAN_APPROVAL_STATUS" NUMBER(18,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6), 
	"REVISION_NUMBER" NUMBER(5,0), 
	"PERSON_TYPE" VARCHAR2(20 BYTE), 
	"GUARANTOR_ID" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."APPLICANT_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."TITLE" IS 'Title of the applicant. Example:  Mr., Ms., Mrs.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."FIRST_NAME" IS 'First name of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."MIDDLE_NAME" IS 'Middle name of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."LAST_NAME" IS 'Last name of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."DATE_OF_BIRTH" IS 'Date of birth of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."MOBILE_NUMBER" IS 'Mobile number of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."HOME_PHONE_NUMBER" IS 'Home telephone number of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."E_MAIL_ID" IS 'E-mail id of the applicant.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."LOAN_APPROVAL_STATUS" IS 'Status of the loan application.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."PERSON_TYPE" IS 'Type of the person. Example: Applicant, Guarantor.';
   COMMENT ON COLUMN "SYSTEM"."TSL_APLCNT_PER_DETAILS"."GUARANTOR_ID" IS 'Reference to APPLICANT_ID of guarantor in TSL_APLCNT_PER_DETAILS table.';
--------------------------------------------------------
--  DDL for Table TSL_CREDIT_CHK_SUM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_CREDIT_CHK_SUM" 
   (	"CREDIT_CHECK_ID" NUMBER(18,0), 
	"APPLICANT_ID" NUMBER(18,0), 
	"AGENCY_ID" NUMBER, 
	"CREDIT_RATING" VARCHAR2(100 BYTE), 
	"CREDIT_SCORE" NUMBER(10,0), 
	"COMMENTS" VARCHAR2(500 BYTE), 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."CREDIT_CHECK_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."APPLICANT_ID" IS 'Reference to APPLICANT_ID in TSL_APLCNT_PER_DETAILS table.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."AGENCY_ID" IS 'Reference to AGENCY_ID in TSL_TP_CRED_CHK_AGENCIES.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."CREDIT_RATING" IS 'Credit  rating provided by agenc';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."CREDIT_SCORE" IS 'Credit  score proivded by agency.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."COMMENTS" IS 'Comments from the agency.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_CREDIT_CHK_SUM"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Table TSL_EMLOYMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_EMLOYMENT_TYPE" 
   (	"EMPLOYMENT_TYPE_ID" NUMBER(18,0), 
	"EMPLOYMENT_TYPE_NAME" VARCHAR2(20 BYTE), 
	"DATA_SOURCE" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_EMLOYMENT_TYPE"."EMPLOYMENT_TYPE_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_EMLOYMENT_TYPE"."EMPLOYMENT_TYPE_NAME" IS 'Type of en employment.';
   COMMENT ON COLUMN "SYSTEM"."TSL_EMLOYMENT_TYPE"."DATA_SOURCE" IS 'Data partition across table indicate who provided the data.';
--------------------------------------------------------
--  DDL for Table TSL_LOAN_AGREEMENTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_LOAN_AGREEMENTS" 
   (	"LOAN_AGRMT_REF_ID" NUMBER(18,0), 
	"APPLICANT_ID" NUMBER(18,0), 
	"LOAN_TYPE_ID" NUMBER, 
	"AGRMT_START_DATE" DATE, 
	"AGRMT_END_DATE" DATE, 
	"LOAN_TERM_MONTHS" NUMBER(5,0), 
	"LOAN_TERM_YEARS" NUMBER(3,0), 
	"LOAN_AMOUNT" NUMBER(19,4), 
	"INTEREST_RATE" NUMBER(19,4), 
	"ARRANGEMENT_FEE" NUMBER(19,4), 
	"PREMIUM_ARRANGE_FEE" NUMBER(19,4), 
	"QUICK_FUND_TXR_FEE" NUMBER(19,4), 
	"EARLY_REPAY_FEE" NUMBER(19,4), 
	"MISSED_PAY_FEE" NUMBER(19,4), 
	"PAY_PROTEC_INSUR_REQ_FLAG" VARCHAR2(1 BYTE), 
	"RELATIONSHIP_MANAGER" NUMBER(18,0), 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."LOAN_AGRMT_REF_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."APPLICANT_ID" IS 'Reference to APPLICANT_ID in TSL_APLCNT_PER_DETAILS table.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."LOAN_TYPE_ID" IS 'Reference to LOAN_TYPE_ID in TSL_LOAN_TYPES table.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."AGRMT_START_DATE" IS 'Loan agreement start date.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."AGRMT_END_DATE" IS 'Loan agreement expiry date. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."LOAN_TERM_MONTHS" IS 'Loan tenure in months.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."LOAN_TERM_YEARS" IS 'Loan tenure in years.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."LOAN_AMOUNT" IS 'Loan amount granted to the customer.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."INTEREST_RATE" IS 'Interest rate for the loan.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."ARRANGEMENT_FEE" IS 'Loan arrangement fee.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."PREMIUM_ARRANGE_FEE" IS 'Pememiumn loan arrangment fee.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."QUICK_FUND_TXR_FEE" IS 'Fee to quicky transfer the funds to the applicant account.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."EARLY_REPAY_FEE" IS 'Fee for the early repayment of the loan.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."MISSED_PAY_FEE" IS 'Fee for the missed payment.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."PAY_PROTEC_INSUR_REQ_FLAG" IS 'Does this loan require payment protection insurance.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."RELATIONSHIP_MANAGER" IS 'Customer relationship manager.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_AGREEMENTS"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Table TSL_LOAN_APPROVAL_STATUSES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES" 
   (	"STAUS_TYPE_ID" NUMBER(18,0), 
	"STAUS_TYPE_NAME" VARCHAR2(20 BYTE), 
	"DATA_SOURCE_ID" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES"."STAUS_TYPE_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES"."STAUS_TYPE_NAME" IS 'Loan approval status. Example: Approved, Pending, Declined. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES"."DATA_SOURCE_ID" IS 'Data partition across table indicate who provided the data.';
--------------------------------------------------------
--  DDL for Table TSL_LOAN_PURPOSE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_LOAN_PURPOSE" 
   (	"LOAN_PURPOSE_ID" NUMBER(18,0), 
	"LOAN_PURPOSE_NAME" VARCHAR2(240 BYTE), 
	"DATA_PARTITION" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_PURPOSE"."LOAN_PURPOSE_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_PURPOSE"."LOAN_PURPOSE_NAME" IS 'Purpose of the loan.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_PURPOSE"."DATA_PARTITION" IS 'Data partition across table indicate who provided the data. ';
--------------------------------------------------------
--  DDL for Table TSL_LOAN_TYPES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_LOAN_TYPES" 
   (	"LOAN_TYPE_ID" NUMBER, 
	"LOAN_TYPE_CODE" VARCHAR2(120 BYTE), 
	"LOAN_TYPE_NAME" VARCHAR2(240 BYTE), 
	"LOAN_TYPE_DESCRIPTION" VARCHAR2(500 BYTE), 
	"LOAN_CATEGORY" VARCHAR2(60 BYTE), 
	"LOAN_BASED_ON" VARCHAR2(60 BYTE), 
	"LOAN_MIN_TERM" NUMBER(3,0), 
	"LOAN_MAX_TERM" NUMBER(3,0), 
	"LOAN_MIN_AMOUNT" NUMBER(19,4), 
	"LOAN_MAX_AMOUNT" NUMBER(19,4), 
	"MIN_INTEREST_RATE" NUMBER(19,4), 
	"MAX_INTEREST_RATE" NUMBER(19,4), 
	"ARRANGE_MIN_FEE" NUMBER(19,4), 
	"ARRANGE_FEE_PERCENT" NUMBER(19,4), 
	"PREMIUM_ARRANGE_FEE" NUMBER(19,4), 
	"QUICK_FUND_TXR_FEE" NUMBER(19,4), 
	"EARLY_REPAY_MIN_FEE" NUMBER(19,4), 
	"EARLY_REPAY_PERCENT" NUMBER(19,4), 
	"MISSED_PAY_MIN_FEE" NUMBER(19,4), 
	"MISSED_PAY_PERCENT" NUMBER(19,4), 
	"PAY_PROTEC_INSUR_REQ_FLAG" VARCHAR2(1 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_TYPE_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_TYPE_CODE" IS 'Short name of the loan type.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_TYPE_NAME" IS 'Name of the loan type.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_TYPE_DESCRIPTION" IS 'Description of the loan type.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_CATEGORY" IS 'Loan type category. Example: Personal, Home Owner Vehicle,Gurantor';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_BASED_ON" IS 'Loan is secured or unsecured.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_MIN_TERM" IS 'Minimum loan repayment period allowed.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_MAX_TERM" IS 'Maximum loan repayment period allowed.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_MIN_AMOUNT" IS 'Minimum loan amount allowed to borrow.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."LOAN_MAX_AMOUNT" IS 'Maximum loan amount allowed to borrow.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."MIN_INTEREST_RATE" IS 'Minimum interest rate offered.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."MAX_INTEREST_RATE" IS 'Maximum interest rate offered.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."ARRANGE_MIN_FEE" IS 'Minimum arragment or setup fee.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."ARRANGE_FEE_PERCENT" IS 'Percentage of the loan amount to be paid for arrangment or setup fee.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."PREMIUM_ARRANGE_FEE" IS 'Premium fee to process the loan application on fast track.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."QUICK_FUND_TXR_FEE" IS 'Fee to quicky transfer the funds to the applicant account.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."EARLY_REPAY_MIN_FEE" IS 'Fee for the early repayment of the loan.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."EARLY_REPAY_PERCENT" IS 'Percentage of the loan amount to be paid for early repayment. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."MISSED_PAY_MIN_FEE" IS 'Minimum fee for the missed payment. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."MISSED_PAY_PERCENT" IS 'Percentage of the loan amount to be paid for missed repayment. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."PAY_PROTEC_INSUR_REQ_FLAG" IS 'Does this loan require payment protection insurance.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."EFFECTIVE_START_DATE" IS 'Effective start of the loan.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."EFFECTIVE_END_DATE" IS 'Effective end date of the loan.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_LOAN_TYPES"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Table TSL_STAFF_DETAIL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_STAFF_DETAIL" 
   (	"PERSON_ID" NUMBER(18,0), 
	"TITLE" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(240 BYTE), 
	"MIDDLE_NAME" VARCHAR2(240 BYTE), 
	"LAST_NAME" VARCHAR2(240 BYTE), 
	"STAFF_JOB_ROLE" NUMBER(18,0), 
	"WORK_PHONE_NUMBER" VARCHAR2(60 BYTE), 
	"WORK_DESK_NUMBER" VARCHAR2(50 BYTE), 
	"WORK_LOCATION" VARCHAR2(240 BYTE), 
	"LINE_MANAGER" NUMBER(18,0), 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."PERSON_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."TITLE" IS 'Title of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."FIRST_NAME" IS 'First name of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."MIDDLE_NAME" IS 'Middle name of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."LAST_NAME" IS 'Last name of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."STAFF_JOB_ROLE" IS 'Job role the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."WORK_PHONE_NUMBER" IS 'Work phone number of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."WORK_DESK_NUMBER" IS 'Work desk number of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."WORK_LOCATION" IS 'Work location of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."LINE_MANAGER" IS 'Line manager of the staff.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_DETAIL"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Table TSL_STAFF_JOB_ROLES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_STAFF_JOB_ROLES" 
   (	"STAFF_JOB_ROLE_ID" NUMBER(18,0), 
	"STAFF_JOB_ROLE_NAME" VARCHAR2(240 BYTE), 
	"STAFF_JOB_ROLE_CODE" VARCHAR2(120 BYTE), 
	"STAFF_JOB_ROLE_DESCRIPTION" VARCHAR2(500 BYTE), 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."STAFF_JOB_ROLE_ID" IS 'System generated unique ID.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."STAFF_JOB_ROLE_NAME" IS 'Name of the job.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."STAFF_JOB_ROLE_CODE" IS 'Short name of the job.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."STAFF_JOB_ROLE_DESCRIPTION" IS 'Description of job. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_STAFF_JOB_ROLES"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Table TSL_TP_CRED_CHK_AGENCIES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES" 
   (	"TP_AGENCY_ID" NUMBER(18,0), 
	"AGENCY_NAME" VARCHAR2(250 BYTE), 
	"AGENCY_CODE" VARCHAR2(120 BYTE), 
	"AGENCY_DESCRIPTION" VARCHAR2(500 BYTE), 
	"REST_URI" VARCHAR2(500 BYTE), 
	"REST_VERSION" VARCHAR2(10 BYTE), 
	"REST_REF_DOC_URL" VARCHAR2(500 BYTE), 
	"REVISION_NUMBER" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CHANGED_BY" VARCHAR2(256 BYTE), 
	"CHANGED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."TP_AGENCY_ID" IS 'System generated unique key.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."AGENCY_NAME" IS 'Name of the agency.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."AGENCY_CODE" IS 'Short name of the agency.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."AGENCY_DESCRIPTION" IS 'Description of the agency.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."REST_URI" IS 'URI of the rest resource.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."REST_VERSION" IS 'Version of the rest resource.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."REST_REF_DOC_URL" IS 'Reference document URL for the REST resource.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."REVISION_NUMBER" IS 'How many times the record was updated. ';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."CREATED_BY" IS 'The user who has created the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."CREATION_DATE" IS 'Date and time when the record is created.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."CHANGED_BY" IS 'The user who has changed the record.';
   COMMENT ON COLUMN "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES"."CHANGED_DATE" IS 'Date and time when the record is changed. ';
--------------------------------------------------------
--  DDL for Index TSL_APLCNT_ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_APLCNT_ADDRESS_PK" ON "SYSTEM"."TSL_APLCNT_ADDRESS" ("APLCNT_ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_APLCNT_CREDIT_CHKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_APLCNT_CREDIT_CHKS_PK" ON "SYSTEM"."TSL_CREDIT_CHK_SUM" ("CREDIT_CHECK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_APLCNT_FIN_DTLS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_APLCNT_FIN_DTLS_PK" ON "SYSTEM"."TSL_APLCNT_FIN_DTLS" ("FIN_DETAILS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_APLCNT_PER_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_APLCNT_PER_DETAILS_PK" ON "SYSTEM"."TSL_APLCNT_PER_DETAILS" ("APPLICANT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_EMLOYMENT_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_EMLOYMENT_TYPE_PK" ON "SYSTEM"."TSL_EMLOYMENT_TYPE" ("EMPLOYMENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_LOAN_AGREEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_LOAN_AGREEMENTS_PK" ON "SYSTEM"."TSL_LOAN_AGREEMENTS" ("LOAN_AGRMT_REF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_LOAN_APPROVAL_STATUSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES_PK" ON "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES" ("STAUS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_LOAN_PURPOSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_LOAN_PURPOSE_PK" ON "SYSTEM"."TSL_LOAN_PURPOSE" ("LOAN_PURPOSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_LOAN_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_LOAN_TYPES_PK" ON "SYSTEM"."TSL_LOAN_TYPES" ("LOAN_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_STAFF_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_STAFF_DETAIL_PK" ON "SYSTEM"."TSL_STAFF_DETAIL" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_STAFF_JOB_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_STAFF_JOB_ROLES_PK" ON "SYSTEM"."TSL_STAFF_JOB_ROLES" ("STAFF_JOB_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TSL_TP_CRED_CHK_AGENCIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES_PK" ON "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES" ("TP_AGENCY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TSL_APLCNT_ADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_APLCNT_ADDRESS" MODIFY ("APLCNT_ADDRESS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_ADDRESS" MODIFY ("APPLICANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_ADDRESS" ADD CONSTRAINT "TSL_APLCNT_ADDRESS_PK" PRIMARY KEY ("APLCNT_ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_APLCNT_FIN_DTLS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_APLCNT_FIN_DTLS" MODIFY ("FIN_DETAILS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_FIN_DTLS" MODIFY ("APPLICANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_FIN_DTLS" ADD CONSTRAINT "TSL_APLCNT_FIN_DTLS_PK" PRIMARY KEY ("FIN_DETAILS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_APLCNT_PER_DETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" MODIFY ("APPLICANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" ADD CONSTRAINT "TSL_APLCNT_PER_DETAILS_PK" PRIMARY KEY ("APPLICANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_CREDIT_CHK_SUM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_CREDIT_CHK_SUM" MODIFY ("CREDIT_CHECK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_CREDIT_CHK_SUM" ADD CONSTRAINT "TSL_APLCNT_CREDIT_CHKS_PK" PRIMARY KEY ("CREDIT_CHECK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_EMLOYMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_EMLOYMENT_TYPE" MODIFY ("EMPLOYMENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_EMLOYMENT_TYPE" ADD CONSTRAINT "TSL_EMLOYMENT_TYPE_PK" PRIMARY KEY ("EMPLOYMENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_LOAN_AGREEMENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_LOAN_AGREEMENTS" MODIFY ("LOAN_AGRMT_REF_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_LOAN_AGREEMENTS" ADD CONSTRAINT "TSL_LOAN_AGREEMENTS_PK" PRIMARY KEY ("LOAN_AGRMT_REF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_LOAN_APPROVAL_STATUSES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES" MODIFY ("STAUS_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES" ADD CONSTRAINT "TSL_LOAN_APPROVAL_STATUSES_PK" PRIMARY KEY ("STAUS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_LOAN_PURPOSE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_LOAN_PURPOSE" MODIFY ("LOAN_PURPOSE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_LOAN_PURPOSE" ADD CONSTRAINT "TSL_LOAN_PURPOSE_PK" PRIMARY KEY ("LOAN_PURPOSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_LOAN_TYPES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_LOAN_TYPES" MODIFY ("LOAN_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_LOAN_TYPES" ADD CONSTRAINT "TSL_LOAN_TYPES_PK" PRIMARY KEY ("LOAN_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_STAFF_DETAIL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_STAFF_DETAIL" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_STAFF_DETAIL" ADD CONSTRAINT "TSL_STAFF_DETAIL_PK" PRIMARY KEY ("PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_STAFF_JOB_ROLES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_STAFF_JOB_ROLES" MODIFY ("STAFF_JOB_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_STAFF_JOB_ROLES" ADD CONSTRAINT "TSL_STAFF_JOB_ROLES_PK" PRIMARY KEY ("STAFF_JOB_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TSL_TP_CRED_CHK_AGENCIES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES" MODIFY ("TP_AGENCY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES" ADD CONSTRAINT "TSL_TP_CRED_CHK_AGENCIES_PK" PRIMARY KEY ("TP_AGENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TSL_APLCNT_ADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_APLCNT_ADDRESS" ADD CONSTRAINT "TSL_APLCNT_ADDRESS_FK1" FOREIGN KEY ("APPLICANT_ID")
	  REFERENCES "SYSTEM"."TSL_APLCNT_PER_DETAILS" ("APPLICANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TSL_APLCNT_FIN_DTLS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_APLCNT_FIN_DTLS" ADD CONSTRAINT "TSL_APLCNT_FIN_DTLS_FK1" FOREIGN KEY ("APPLICANT_ID")
	  REFERENCES "SYSTEM"."TSL_APLCNT_PER_DETAILS" ("APPLICANT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."TSL_APLCNT_FIN_DTLS" ADD CONSTRAINT "TSL_APLCNT_FIN_DTLS_FK2" FOREIGN KEY ("EMPLOYMENT_TYPE")
	  REFERENCES "SYSTEM"."TSL_EMLOYMENT_TYPE" ("EMPLOYMENT_TYPE_ID") ENABLE;
  ALTER TABLE "SYSTEM"."TSL_APLCNT_FIN_DTLS" ADD CONSTRAINT "TSL_APLCNT_FIN_DTLS_FK3" FOREIGN KEY ("LOAN_PURPOSE")
	  REFERENCES "SYSTEM"."TSL_LOAN_PURPOSE" ("LOAN_PURPOSE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TSL_APLCNT_PER_DETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" ADD CONSTRAINT "TSL_APLCNT_PER_DETAILS_FK1" FOREIGN KEY ("GUARANTOR_ID")
	  REFERENCES "SYSTEM"."TSL_APLCNT_PER_DETAILS" ("APPLICANT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."TSL_APLCNT_PER_DETAILS" ADD CONSTRAINT "TSL_APLCNT_PER_DETAILS_FK2" FOREIGN KEY ("LOAN_APPROVAL_STATUS")
	  REFERENCES "SYSTEM"."TSL_LOAN_APPROVAL_STATUSES" ("STAUS_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TSL_CREDIT_CHK_SUM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_CREDIT_CHK_SUM" ADD CONSTRAINT "TSL_CREDIT_CHK_SUM_FK1" FOREIGN KEY ("AGENCY_ID")
	  REFERENCES "SYSTEM"."TSL_TP_CRED_CHK_AGENCIES" ("TP_AGENCY_ID") ENABLE;
  ALTER TABLE "SYSTEM"."TSL_CREDIT_CHK_SUM" ADD CONSTRAINT "TSL_CREDIT_CHK_SUM_FK2" FOREIGN KEY ("APPLICANT_ID")
	  REFERENCES "SYSTEM"."TSL_APLCNT_PER_DETAILS" ("APPLICANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TSL_LOAN_AGREEMENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_LOAN_AGREEMENTS" ADD CONSTRAINT "TSL_LOAN_AGREEMENTS_FK1" FOREIGN KEY ("APPLICANT_ID")
	  REFERENCES "SYSTEM"."TSL_APLCNT_PER_DETAILS" ("APPLICANT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."TSL_LOAN_AGREEMENTS" ADD CONSTRAINT "TSL_LOAN_AGREEMENTS_FK2" FOREIGN KEY ("LOAN_TYPE_ID")
	  REFERENCES "SYSTEM"."TSL_LOAN_TYPES" ("LOAN_TYPE_ID") ENABLE;
  ALTER TABLE "SYSTEM"."TSL_LOAN_AGREEMENTS" ADD CONSTRAINT "TSL_LOAN_AGREEMENTS_FK3" FOREIGN KEY ("RELATIONSHIP_MANAGER")
	  REFERENCES "SYSTEM"."TSL_STAFF_DETAIL" ("PERSON_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TSL_STAFF_DETAIL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TSL_STAFF_DETAIL" ADD CONSTRAINT "TSL_STAFF_DETAIL_FK2" FOREIGN KEY ("LINE_MANAGER")
	  REFERENCES "SYSTEM"."TSL_STAFF_DETAIL" ("PERSON_ID") ENABLE;
